name: Build Mac Application

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install required libraries
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy matplotlib scipy pyinstaller

      - name: Build the Mac App (Native Bundle, NO onefile)
        run: |
          pyinstaller --windowed --clean --name "BioOil_TAN_Analyzer" TAN_Calculator_1_0.py

      - name: Create Mac DMG Installer
        run: |
          cd dist
          hdiutil create -volname "BioOil Analyzer" -srcfolder BioOil_TAN_Analyzer.app -ov -format UDZO BioOil_TAN_Analyzer.dmg

      - name: Upload the finished DMG
        uses: actions/upload-artifact@v4
        with:
          name: BioOil_TAN_Analyzer_Mac_Installer
          path: dist/BioOil_TAN_Analyzer.dmg
